#!/bin/bash
set -xuo pipefail

mkdir -p notebooks
# because of symlinks and being in the container, this is where the Binder
# instance thinks the data should go.
NEMOS_DATA_DIR=/home/jovyan/data python ccn-software-fens-2026/scripts/setup.py
cp -r ccn-software-fens-2026/notebooks/group_projects/ ./notebooks/
cp -r ccn-software-fens-2026/notebooks/live_coding/ ./notebooks/
sed -i 's|../../docs/source/_static/|../../ccn-software-fens-2026/docs/source/_static/|g' notebooks/*/*ipynb
